name: Build and Test

on:
  push:
    branches:
      - master
    tags: []
  pull_request:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0

      - name: Check out code
        uses: actions/checkout@v3

      - name: Lint Go Code
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: ./api

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0

      - name: Check out code
        uses: actions/checkout@v3

      - name: Build
        run: cd api && go build -v ./...
